services:
  ww-walk-postgres:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - walk-service-postgis_data

  mongo:
    image: mongo:5.2.1
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - walk-service-mongo_data:/data/db
    restart: unless-stopped

volumes:
  walk-service-mongo_data:
  walk-service-postgis_data: