services:
  ww-walk-postgres:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_DB=walk-postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - walk-service-postgis_data

  ww-mongodb:
    image: mongo:5.2.1
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_PORT=27017
    volumes:
      - walk-service-mongo_data:/data/db
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbit_data:/rabbit/data
    restart: unless-stopped

volumes:
  walk-service-mongo_data:
  walk-service-postgis_data:
  rabbit_data: