stages:
  - build

variables:
  DOCKER_AUTH_CONFIG: '{"auths":{"https://index.docker.io/v1/":{"auth":"${DOCKER_AUTH_STRING}"}}}'
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker compose build backend-user-service --no-cache
  only:
    - feature/WANDER-23

