spring:
  application:
    name: ww-walk-service
  datasource:
    url: jdbc:postgresql://localhost:5432/agona_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    mongodb:
      uri: mongodb://localhost:27017/ww-walk-service
      auto-index-creation: true
  liquibase:
    change-log: "../../../"

walk:
  record:
    location:
      max-sse-timeout: 90_000
      reconnection-time: 3_000