spring:
  application:
    name: ww-walk-service
  datasource:
    url: jdbc:postgresql://localhost:5432/agona_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    mongodb:
      uri: mongodb://localhost:27017/ww-walk-service
      # uri: mongodb://localhost:${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@localhost:${MONGO_PORT}/ww-walk-service
      auto-index-creation: true
  liquibase:
    change-log: classpath:/db/changelog/walk-service/changelog-master.yaml
  kafka:
    consumer:
      bootstrap-servers: localhost:9092, localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: walk-service-events
      properties:
        spring-json-trusted-packages: com.technokratos.event
    producer:
      bootstrap-servers: localhost:9092, localhost:9094
      acks: all
      retries: 10
      properties:
        delivery-timeout-ms: 20000
        linger-ms: 0
        request-timeout-ms: 10000
        enable-idempotence: true
        max-in-flight-requests-per-connection: 5

walk:
  record:
    location:
      max-sse-timeout: 90_000
      reconnection-time: 3_000
      max-walk-expires-time: 3
app:
  url:
    base-url: "https://wonderful-wander.ru"
    walk-acceptation-url: "/api/walks/{walkId}/participant/{participantId}/accept"
    subscribers-retrieve-url: "/api/users/{userId}/following"