spring:
  application:
    name: ww-walk-service
  datasource:
    url: jdbc:postgresql://localhost:5432/agona_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  data:
    mongodb:
      uri: mongodb://localhost:27017/walk-service-db
